## Statistics Demonstrations


- Distributions (Binomial and Normal)
- Random Numbers
- Combinations

In [3]:
#Importing the libraries
import numpy as np
#Introducing the scipy.stats library
import scipy.stats as ss

### Distributions

##### 1. Binomial Distribution

A `binomial distribution` is utilised when the following conditions are met

- Total number of trials is fixed at **n**

- Each trial is binary, i.e., has only two possible outcomes - success or failure

- Probability of success is same in all trials, denoted by **p**

Now if you want to find the probability of **r** successes or `P(X = r)`, then you can use the following formula

![Binomial Probability Formula](https://raw.githubusercontent.com/emchandrakant/scipy-statistics/master/images/binom.JPG?token=GHSAT0AAAAAAB5FOJ2VSHFMSWDAPLDSVWMOY7GENZQ)

In [4]:
#Calculating probabilites
#P (X = r)
n = 10
p = 0.4
r = 4

In [5]:
#To calculate the probability we'll use the binom.pmf (Probability mass function)
?ss.binom.pmf

In [6]:
ss.binom.pmf(r,n,p)

0.25082265599999987

In [7]:
#round the values
np.round(ss.binom.pmf(r,n,p),3)

0.251

In [8]:
#Calculating Probabilites
# P(X < = r)
#Use the binom.cdf function (Cumulative distribution function)
?ss.binom.cdf

In [9]:
#Calculating the probabilities
np.round(ss.binom.cdf(r,n,p),3)

0.633

###### 2. Normal Distribution

![Normal Distribution](https://raw.githubusercontent.com/emchandrakant/scipy-statistics/master/images/normd.jpg?token=GHSAT0AAAAAAB5FOJ2U23GP63DV2WAWKRDKY7GEOOQ)

Let's say you're given a normal distribution with

- mean = M
- standard deviation = sd

Now you are given a value **x** and you want to compute P(X<=**x**)

In [10]:
M = 60
sd = 10
x = 40

In [50]:
#To compute P(X<=x) we use the ss.norm.cdf function
?ss.norm.cdf

In [11]:
ss.norm.cdf(x,M,sd)

0.0227501319481792

In [12]:
ss.norm(60,10).cdf(40)

0.0227501319481792

In [12]:
ss.norm.cdf(80,60,10) - ss.norm.cdf(40,60,10)

0.9544997361036416

### Random Numbers

In [ ]:
#Generate random numbers belonging to a particular distribution

In [51]:
?np.random

##### 1. Binomial Distribution

For binomial distribution, given the value of **n** (the number of trials) and **p** ( the probability of success for each trial) we can generate random sequence of  possible number of successes **r** when we run this experiment multiple times.

In [52]:
?np.random.binomial

In [13]:
#Generate 10 random numbers from the binomial distribution with n = 10 and p = 0.4 
n = 10
p = 0.4
size = 10

In [14]:
#We'll use np.random.binomial
np.random.binomial(n,p,size)

array([4, 3, 4, 3, 2, 6, 6, 4, 4, 6])

###### 2. Normal Distribution

For normal distribution, given the value of mean (**M**) and standard deviation (**sd**) we can generate random sequence of values belonging to this distribution

In [53]:
?np.random.normal

In [15]:
#Generate 10 random numbers from the normal distribution with M = 60 and sd = 10
M = 60
sd  = 10

In [21]:
np.random.normal(M,sd,10)

array([52.66227303, 55.69164076, 53.89002497, 59.35743014, 67.60313138,
       70.21599659, 47.89525442, 53.26656768, 61.87438073, 51.96210961])

###### Seed

In order to fix the output we can set the `seed` value

In [57]:
?np.random.seed

In [41]:
seed = 100
np.random.seed(seed)

In [40]:
np.random.normal(M,sd,10)

array([42.50234527, 63.42680403, 71.53035803, 57.47563963, 69.81320787,
       65.14218841, 62.21179669, 49.29956669, 58.10504169, 62.55001444])

In [42]:
np.random.normal(M,sd,10)

array([42.50234527, 63.42680403, 71.53035803, 57.47563963, 69.81320787,
       65.14218841, 62.21179669, 49.29956669, 58.10504169, 62.55001444])

The seed has to be initialised each time you run the code to get the same output

### Combinations

Given a list containing **n** number of objects, we can find all the combinations of size **r**

In [43]:
from itertools import combinations

In [70]:
?combinations

In [44]:
alpha = 'ABCD'

In [45]:
p = combinations(alpha,2)

In [46]:
p

In [47]:
#To print the combinations
list(p)

[('A', 'B'), ('A', 'C'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D')]

In [40]:
alpha = ['A','B','C','D']

In [75]:
p = combinations(alpha,2)

In [76]:
list(p)

[('A', 'B'), ('A', 'C'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D')]

In [48]:
num = [1,2,3]
num

[1, 2, 3]

In [49]:
list(combinations(num,2))

[(1, 2), (1, 3), (2, 3)]

In [50]:
for c in combinations(num,2):
    if 2 in c:
        print(c)

(1, 2)
(2, 3)


In [46]:
for c in combinations(alpha,2):
    if 'A' in c:
        print(c)

('A', 'B')
('A', 'C')
('A', 'D')
